# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"

    # Limit number of open PRs
    open-pull-requests-limit: 10

    # Group updates to reduce PR noise
    groups:
      # Group all minor and patch updates together
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      # Group dev dependencies separately
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"

    # Labels for PR organization
    labels:
      - "dependencies"
      - "automated"

    # Commit message configuration
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

    # Package-specific rules
    ignore:
      # Ignore major versions of critical packages that might have breaking changes
      - dependency-name: "commander"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      # Express v5 is still in beta, stick with v4 for now
      - dependency-name: "express"
        versions: ["5.x"]

    # Allow specific dependency types
    allow:
      # Always allow security updates
      - dependency-type: "all"

    # Reviewers and assignees
    reviewers:
      - "slamb2k"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"

    # Limit number of open PRs
    open-pull-requests-limit: 5

    # Labels for PR organization
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

    # Commit message configuration
    commit-message:
      prefix: "chore"
      include: "scope"

    # Group all action updates together
    groups:
      actions:
        patterns:
          - "*"